name: Teste de Software
run-name: ${{ github.actor }} está executando a pipeline de teste
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Iniciando a pipeline de teste"
      - run: py --version
      - run: py Teste_component/componente.py
